### ISSUE TITLE
team class matchlist and playerlist bug

### ISSUE THREAD

**Issue by huyidi** [CS2113-AY1819S2-M11-1/main#116]
updated matches and edited plays are not in matchlist and playerlist in team class, ie the change is not reflected. same as delete/clear. might want to add stuff in Addressbook file to respond to changes of edit/update of matches and players.

**Comment by yingrong1996** [comment]
Changes has been made to resolve the mentioned issue.

**Comment by E0176106** [comment]
Close issue if resolved

**Comment by warheade** [comment]
resolved and closed
